### ISSUE TITLE
Success is set to true on error response

### ISSUE THREAD

**Issue by joakimmillen** [imgarylai/use-mailchimp-form#168] opened 2022-03-25 10:58 UTC
This is a sample from the code i'm using

```
   const { loading, error, success, message, handleSubmit } = useMailChimpForm(
    url
  );

  const { fields, handleFieldChange } = useFormFields({
    EMAIL: "",
  });

  const onFormSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    if (e) e.preventDefault();
    handleSubmit(fields);
  };
````

When I try to signup using the email `test@asd` i get the data from the `useMailChimpForm`:

```
success: true
error: false
message: "0 - The domain portion of the email address is invalid (the portion after the @: asd)"
```

But if i check the network tab i get the response:

```
jsonp_1648205260384_92116({"result":"error","msg":"0 - The domain portion of the email address is invalid (the portion after the @: asd)"})
```

And here we can clearly see that the response is "error".

**Expected result**
I expect the result from the `useMailChimpForm` to be

```
success: false
error: true
message: "0 - The domain portion of the email address is invalid (the portion after the @: asd)"
```

since it is in fact an error.

**Comment by imgarylai** [comment] 2022-03-26 05:16
Thank you for providing this detailed inspection. My first thought of this situation was because the current implementation decides success/error due to the HTTP status, but not from the Mailchimp result. 

Will check list of errors on the Mailchimp side.

**Comment by edward-simpson** [comment] 2022-10-19 10:10
I'm also seeing this:

`jsonp_1666174109184_1195({"result":"error","msg":"Recipient \"\" has too many recent signup requests"})`

**Comment by edward-simpson** [comment] 2022-10-19 10:22
The issue is that you're checking for `response.ok` which should be fine, but mailchimp returns 200 even if there's an error:
![Screenshot 2022-10-19 at 11 20 53](https://user-images.githubusercontent.com/26060776/196665247-257b2dbd-d36e-4cf1-9afc-2aa00f319699.png)

I'll pop together a PR to fix

**Comment by edward-simpson** [comment] 2022-10-19 10:59
https://github.com/imgarylai/use-mailchimp-form/pull/320

**Comment by RosarioMeyerArana** [comment] 2022-11-08 16:34
I'm facing the same issue over here, can you please update with the mentioned PR? @imgarylai

**Comment by imgarylai** [comment] 2022-11-28 00:13
@edward-simpson @RosarioMeyerArana @joakimmillen Thank you for bringing this up. 
The CR was merged to handle this situation.

**Closed by imgarylai** 2022-11-28 00:13 UTC
